export const LOAD_ALL_CHARACTER_START = 'CHARACTER/LOAD_ALL_CHARACTER_START';
export const LOAD_ALL_CHARACTER_SUCCESS = 'CHARACTER/LOAD_ALL_CHARACTER_SUCCESS';
export const LOAD_ALL_CHARACTER_ERROR = 'CHARACTER/LOAD_ALL_CHARACTER_ERROR';
